import 'package:flutter/material.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});
  @override State<HomeScreen> createState()=>_HomeScreenState();
}
class _HomeScreenState extends State<HomeScreen>{
  int mood=-1; final moods=['😊','🙂','😐','😔','😣','😰'];
  @override Widget build(BuildContext context){
    final c=Theme.of(context).colorScheme;
    return Scaffold(body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(20,18,20,110),children:[
      Row(children:[CircleAvatar(radius:24,backgroundColor:c.primaryContainer,child:Icon(Icons.psychology_rounded,color:c.primary)),const SizedBox(width:12),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Good morning',style:TextStyle(fontSize:14)),Text('Welcome to BrainByte',style:TextStyle(fontSize:22,fontWeight:FontWeight.w800))])),IconButton(onPressed:(){},icon:const Icon(Icons.notifications_none_rounded))]),
      const SizedBox(height:24),Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:LinearGradient(colors:[c.primary,c.tertiary]),borderRadius:BorderRadius.circular(28)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('A calmer moment starts here',style:TextStyle(color:Colors.white,fontSize:23,fontWeight:FontWeight.w800)),SizedBox(height:8),Text('Check in, breathe, focus or train your memory — at your pace.',style:TextStyle(color:Colors.white70,height:1.4)),SizedBox(height:16),LinearProgressIndicator(value:.62,borderRadius:BorderRadius.all(Radius.circular(12))),SizedBox(height:8),Text('Today’s wellness • 62%',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w600))])),
      const SizedBox(height:24),const Text('How are you feeling?',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:12),SizedBox(height:70,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:moods.length,separatorBuilder:(_,__)=>const SizedBox(width:10),itemBuilder:(ctx,i)=>InkWell(borderRadius:BorderRadius.circular(22),onTap:()=>setState(()=>mood=i),child:AnimatedContainer(duration:const Duration(milliseconds:220),width:62,alignment:Alignment.center,decoration:BoxDecoration(color:mood==i?c.primaryContainer:c.surfaceContainer,borderRadius:BorderRadius.circular(22),border:Border.all(color:mood==i?c.primary:Colors.transparent,width:2)),child:AnimatedScale(scale:mood==i?1.18:1,duration:const Duration(milliseconds:180),child:Text(moods[i],style:const TextStyle(fontSize:29))))))),
      const SizedBox(height:26),const Text('Quick actions',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:12),GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),mainAxisSpacing:12,crossAxisSpacing:12,childAspectRatio:1.25,children:[_Action(Icons.auto_awesome_rounded,'Talk to BrainByte','Supportive conversation'),_Action(Icons.air_rounded,'Calm Me','Breathing & relaxation'),_Action(Icons.visibility_rounded,'Grounding','5-4-3-2-1 exercise'),_Action(Icons.center_focus_strong_rounded,'Focus','Timer & sessions'),_Action(Icons.extension_rounded,'Brain Games','Memory & patterns'),_Action(Icons.menu_book_rounded,'Journal','Private reflections')]),
      const SizedBox(height:24),Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:c.errorContainer,borderRadius:BorderRadius.circular(24)),child:Row(children:[Icon(Icons.health_and_safety_rounded,color:c.error),const SizedBox(width:14),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Need support?',style:TextStyle(fontWeight:FontWeight.w800,fontSize:17)),Text('Trusted contacts and support resources',style:TextStyle(fontSize:13))])),const Icon(Icons.chevron_right_rounded)])
    ])));
  }
}
class _Action extends StatelessWidget{final IconData icon;final String title,sub;const _Action(this.icon,this.title,this.sub);@override Widget build(BuildContext context){final c=Theme.of(context).colorScheme;return InkWell(borderRadius:BorderRadius.circular(24),onTap:(){},child:Ink(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:c.surfaceContainer,borderRadius:BorderRadius.circular(24)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,color:c.primary,size:27),const Spacer(),Text(title,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:16)),Text(sub,maxLines:1,overflow:TextOverflow.ellipsis,style:TextStyle(fontSize:11,color:c.onSurfaceVariant))])));}}
